---
- include: ssh.yml
  when: nova.enable_ssh|bool

- include: libvirt.yml
  when: nova.compute_driver == "nova.virt.libvirt.LibvirtDriver"

- include: docker.yml
  when: nova.compute_driver == "novadocker.virt.docker.DockerDriver"

- name: install nova data plan requirements
  apt: pkg=sysfsutils

- name: nova instances directory
  file: dest=/var/lib/nova/instances state=directory owner=nova

- name: nbd module
  lineinfile: dest=/etc/modules line="nbd"

- name: probe nbd
  modprobe: name=nbd state=present

- lineinfile: dest=/etc/modules line="nbd"

- modprobe: name=nbd state=present

#added 2 modprobe modules to /etc/modules
- name: br_netfilter module
  lineinfile: dest=/etc/modules line="br_netfilter"

- name: probe br_netfilter
  modprobe: name=br_netfilter state=present

- lineinfile: dest=/etc/modules line="br_netfilter"

- modprobe: name=br_netfilter state=present

- name: ipmi_devintf module
  lineinfile: dest=/etc/modules line="ipmi_devintf"

- name: probe ipmi_devintf
  modprobe: name=ipmi_devintf state=present

- lineinfile: dest=/etc/modules line="ipmi_devintf"

- modprobe: name=ipmi_devintf state=present

# Disable SMT At Boot
- name: Turning SMT mode OFF
  lineinfile: dest=/etc/rc.local line="ppc64_cpu  --smt=off"

- name: enable cinder encryption
  template: src=etc/nova/nova.cinder_encryption.conf dest=/etc/nova/nova.cinder_encryption.conf mode=0640
            owner=root group=nova
  notify: restart nova services
  when: cinder.fixed_key is defined

- name: disable  cinder encryption
  file: dest=/etc/nova/nova.cinder_encryption.conf state=absent
  notify: restart nova services
  when: cinder.fixed_key is not defined

# Invoke services & to make upstart as the default instead of systemd
- name: install upstart-sysv
  apt: pkg=upstart-sysv

- name: install nova-compute service
  upstart_service: name=nova-compute user=nova cmd=/usr/bin/nova-compute
                   config_dirs=/etc/nova

- name: start nova-compute
  service: name=nova-compute state=started

