---
- name: add global proxy
  lineinfile: dest=/etc/environment regexp=^http_proxy=
              state=absent
  when: common.ansible_proxy is defined

- name: ignore proxy for localhost
  lineinfile: dest=/etc/environment regexp=^no_proxy=
              state=absent
  when: common.ansible_proxy is defined