---
- name: ntp.conf include directive
  lineinfile: dest=/etc/ntp.conf
              line="includefile /etc/ntp/cluster.conf" state=present

- name: /etc/ntp directory
  file: dest=/etc/ntp state=directory mode=755 owner=root

#Added changes to create ntp.conf
- name: backup of existing ntp.conf 
  command: cp /etc/ntp.conf /etc/ntp.conf.bak 

- name: create ntp.conf in /etc/ntp.conf with changes incorporated
  template: dest=/etc/ntp.conf
            src=etc/ntp.conf
            mode=644 owner=root

- name: ntp/cluster.conf
  template: dest=/etc/ntp/cluster.conf
            src=etc/ntp/cluster.conf
            mode=644 owner=root
  notify:
    - restart-ntp

- name: ntp service enabled
  service: name=ntp state=started enabled=true
