---
- name: add an apt proxy
  template: src=etc/apt/apt.conf.d/01proxy dest=/etc/apt/apt.conf.d/01proxy
            owner=root group=root mode=0644
  when: common.apt_cache is defined

- name: add global proxy
  lineinfile: dest=/etc/environment regexp=^http_proxy=
              line="http_proxy={{ common.global_proxy|default(common.ansible_proxy) }}"
  when: common.global_proxy is defined or common.ansible_proxy is defined

- name: ignore proxy for localhost
  lineinfile: dest=/etc/environment regexp=^no_proxy=
              line="no_proxy=localhost,127.0.0.0/8,127.0.1.1,127.0.1.1*,local.home"
  when: common.global_proxy is defined or common.ansible_proxy is defined